src/Entity/Consultation.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\ConsultationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ConsultationRepository::class)]
class Consultation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Patient::class)]
#[ORM\JoinColumn(name: 'patient_id', referencedColumnName: 'id')]
private ?Patient $patient = null;
    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Docteur $Docteur = null;

    #[ORM\ManyToOne(inversedBy: 'consultations')]
    private ?Dossiermedical $dossiermedical = null;

    #[ORM\Column(type: 'date')] 
    #[Assert\NotNull(message:"La date ne peut pas être vide")]
    #[Assert\GreaterThanOrEqual("today", message:"La date de consultation ne peut pas être antérieure à aujourd'hui")]
    private ?\DateTimeInterface $date_consultation  = null ;

    #[ORM\Column(length: 255)]
    #[Assert\Regex(
        pattern:"/^[a-zA-Z0-9._%+-]+@gmail\.com$/",
      message:"The email must be in the format example@gmail.com."
      )]
    private ?string $email = null;

   
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getDocteur(): ?Docteur
    {
        return $this->Docteur;
    }

    public function setDocteur(?Docteur $Docteur): static
    {
        $this->Docteur = $Docteur;

        return $this;
    }

    public function getDossiermedical(): ?Dossiermedical
    {
        return $this->dossiermedical;
    }

    public function setDossiermedical(?Dossiermedical $dossiermedical): static
    {
        $this->dossiermedical = $dossiermedical;

        return $this;
    }


    public function getDateConsultation(): ?\DateTimeInterface
    {
        return $this->date_consultation;
    }

    public function setDateConsultation(?\DateTimeInterface $date_consultation): self
    {
        $this->date_consultation = $date_consultation;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

  
}

src/Controller/ConsultationController.php
<?php

namespace App\Controller;

use App\Entity\Consultation;
use App\Form\Consultation1Type;
use App\Repository\ConsultationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Service\MailerService;

#[Route('/consultation')]
class ConsultationController extends AbstractController
{
    #[Route('/telecons', name: 'app_consultation_telecons', methods: ['GET'])]
    public function telecons(ConsultationRepository $consultationRepository): Response
    {
        return $this->render('consultation/teleconsultation.html.twig');
    }

    #[Route('/', name: 'app_consultation_index', methods: ['GET'])]
    public function index(ConsultationRepository $consultationRepository): Response
    {
        $statisticsData = [
            'total_users' => 1000,
            'total_orders' => 500,
            // Add more statistics data as needed
        ];

        // Convert statistics data to JSON
        $statisticsJson = json_encode($statisticsData);

        return $this->render('consultation/index.html.twig', [
            'consultations' => $consultationRepository->findAll(),
            'statisticsJson' => $statisticsJson,

        ]);
    }
    
       

    #[Route('/new', name: 'app_consultation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager,MailerService $mailer): Response
    {
        $consultation = new Consultation();
        $form = $this->createForm(Consultation1Type::class, $consultation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($consultation);
            $entityManager->flush();
            $message="This is your teleconsultation link to meet our doctors, our specialists will come to you in few an gide you throughout your demand.
            
            meet.google.com/kkb-vtni-esz";

            $mailMessage=$message;
            $email=$consultation->getEmail();
            $mailer->sendEmail(content: $mailMessage,to:$email);
            return $this->redirectToRoute('app_consultation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('consultation/new.html.twig', [
            'consultation' => $consultation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_consultation_show', methods: ['GET'])]
    public function show(Consultation $consultation): Response
    {
        return $this->render('consultation/show.html.twig', [
            'consultation' => $consultation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_consultation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Consultation $consultation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Consultation1Type::class, $consultation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_consultation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('consultation/edit.html.twig', [
            'consultation' => $consultation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_consultation_delete', methods: ['POST'])]
    public function delete(Request $request, Consultation $consultation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$consultation->getId(), $request->request->get('_token'))) {
            $consultation->setPatient(null);
            $consultation->setDocteur(null);
            $entityManager->remove($consultation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_consultation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/consultation/_delete_form.html.twig
<form method="post" action="{{ path('app_consultation_delete', {'id': consultation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ consultation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/consultation/_form.html.twig
{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/consultation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Consultation{% endblock %}

{% block body %}
    <h1>Edit Consultation</h1>
<br><br><br><br><br>
    {{ include('consultation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_consultation_index') }}">back to list</a>

    {{ include('consultation/_delete_form.html.twig') }}
{% endblock %}

templates/consultation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Consultation index{% endblock %}

{% block body %}
    <h1>Consultation index</h1>
<br><br><br><br><br>

<center>
  
 <a class="fcc_btn" style=" border:none; background-color: cadetblue; color:#fff; padding:10px 20px; font-size:16px; margin:20px; cursor: pointer;" href="{{ url('app_consultation_telecons') }}">Teleconsultation</a>
                 <a class="fcc_btn" style=" border:none; background-color: cadetblue; color:#fff; padding:10px 20px; font-size:16px; margin:20px; cursor: pointer;" href="{{ url('app_consultation_new') }}">book online consultation</a>
                 <div class="article" style="background-color: #f2f2f2;margin-top: 60px;margin-bottom: 30px; padding: 20px; border-radius: 5px; width:400px; heigth:200px ">
                        <img src="/images/urgent.svg" alt="Description" width="100" height="100" margin-top= "60px" margin-bottom= "360px">

        <p>Pour les situations constituant une URGENCE, nous vous recommandons d’appeler un service d’urgences ou bien e vous adresser au service d’urgence le plus proche de vous.</p>
                  </div> 
                  <h1>Blog</h1>
    
   
    
        <table>

<tbody>

            <tr>
            <td>
    <div class="article" style="background-color: #f2f2f2; padding: 20px; border-radius: 5px; width:400px; heigth:900px ">
        <h2>This is an article created by our precious members</h2>
                <img src="/images/health_worker.svg" alt="Description" width="300" height="200" margin-top= "60px" margin-bottom= "60px">

        <p>My experience with the Dentist was amazingly unforgettable, i would recommand noTreatment</p>
    </div>
    </td>
    
              <td>

    <div class="article" style="background-color: #f2f2f2; padding: 20px; border-radius: 5px; width:400px; heigth:200px ">
        <h2>This is an article created by our precious members</h2>
                        <img src="/images/telecons.svg" alt="Description" width="300" height="200">

        <p>Video Consultation is a life and time saving, no queue waiting. Thank you</p>
    </div>
    </td>
     <td>

    <div class="article" style="background-color: #f2f2f2; padding: 20px; border-radius: 5px; width:400px; heigth:200px ">
        <h2>This is an article created by our precious members</h2>
                        <img src="/images/dossier_med.svg" alt="Description" width="300" height="200">

        <p>I'm more comfortable with my health because i feel safe using these organized doc schedules</p>
    </div>
    </td>
                        </tr>

         
        </tbody>
            </table>
                </center>

<script>
        var body = document.getElementsByTagName("body");
        var div = document.createElement("div");
        var host = window.location.host ? window.location.origin : 'http://localhost/';
        div.innerHTML = `<iframe id="synvision_ai_iframe" name="synvision_ai_iframe" src="http://synvision.ai/chat-iframe?uuid=VNCYgMgf&host=${host}" height = "960px" width = "750px" style="position:fixed;right:0;bottom: 50px;z-index: 100;border:none"></iframe>`;
        document.body.appendChild(div);
    </script>
</div>

    

  <h1 class="display-4">Consultation List</h1>
        <div class="my-5"></div>

        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Patient</th>
                    <th scope="col">Docteur</th>
                    <th scope="col">Dossier medical</th>
                    <th scope="col">Date Consultation</th>
                    <th scope="col">Email</th>

                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for consultation in consultations %}
                    <tr>
                        <td>{{ consultation.id }}</td>
                        <td>{{ consultation.patient }}</td>
                        <td>{{ consultation.docteur }}</td>
                        <td>{{ consultation.dossiermedical.id }}</td>
                        <td>{{ consultation.DateConsultation }}</td>
                        <td>{{ consultation.Email }}</td>

                        <td>
                            <a href="{{ path('app_consultation_show', {'id': consultation.id}) }}" class="btn btn-info btn-sm">
                                {{ 'Voir'|trans }}
                            </a>
                            <a href="{{ path('app_consultation_edit', {'id': consultation.id}) }}" class="btn btn-warning btn-sm">
                                {{ 'Éditer'|trans }}
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="3">{{ 'Aucune consultation trouvée.'|trans }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>


    {% block js %}
  <script src='{{asset('js/telecons.js')}}'></script>

{% endblock %}
 <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div style="background-color: #f0f0f0; border: 1px solid #ccc; padding: 20px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); max-width: 400px;">
            <h1 style="text-align: center;">Statistics</h1>
            <canvas id="statisticsChart" width="400" height="400"></canvas>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var statisticsData = {{ statisticsJson | raw }};
            var ctx = document.getElementById('statisticsChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: ['Online consultation', 'One to One consultation'],
                    datasets: [{
                        label: 'Statistics',
                        data: [statisticsData.total_users, statisticsData.total_orders],
                        backgroundColor: [
                            'rgba(255, 99, 132, 0.5)',
                            'rgba(54, 162, 235, 0.5)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)'
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        y: {
                            beginAtZero: true
                        }
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/consultation/index1.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'Consultation Index'|capitalize }}
{% endblock %}

{% block body %}
    <div class="container mt-5">
    <br><br><br><br><br><br>
        <h1 class="display-4">Consultation List</h1>
        <div class="my-5"></div>

        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Patient_ID</th>
                    <th scope="col">Docteur_ID</th>
                    <th scope="col">Dossier medical ID</th>
                    <th scope="col">Date Consultation</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for consultation in consultations %}
                    <tr>
                        <td>{{ consultation.id }}</td>
                        <td>{{ consultation.patient_id }}</td>
                        <td>{{ consultation.docteur_id }}</td>
                        <td>{{ consultation.dossiermedical_id }}</td>
                        <td>{{ consultation.date_consultation }}</td>
                        <td>
                            <a href="{{ path('app_consultation_show', {'id': consultation.id}) }}" class="btn btn-info btn-sm">
                                {{ 'Voir'|trans }}
                            </a>
                            <a href="{{ path('app_consultation_edit', {'id': consultation.id}) }}" class="btn btn-warning btn-sm">
                                {{ 'Éditer'|trans }}
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="3">{{ 'Aucune consultation trouvée.'|trans }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_consultation_new') }}" class="btn btn-success">
            {{ 'Créer une nouvelle consultation'|trans }}
        </a>
    </div>
{% endblock %}

templates/consultation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Consultation{% endblock %}
 {% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
{% endblock %}
{% block body %}
    <h1>Create new Consultation</h1>
<br><br><br><br><br>
   <center>
   
       <h1>Create new Consultation</h1>

    {{ include('consultation/_form.html.twig') }}

    <a href="{{ path('app_consultation_index') }}">back to list</a>
    
       </center>

    {% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% endblock %}

{% endblock %}

templates/consultation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Consultation{% endblock %}

{% block body %}
    <h1>Consultation</h1>
<br><br><br><br><br>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ consultation.id }}</td>
            </tr>
            <tr>
                <th>Date_consultation</th>
                <td>{{ consultation.dateConsultation }}</td>
            </tr>
            <tr>
                <th>Dossiermedical_id</th>
                <td>{{ consultation.dossiermedical }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ consultation.Email }}</td>
            </tr>
         
         
        </tbody>
    </table>

    <a href="{{ path('app_consultation_index') }}">back to list</a>

    <a href="{{ path('app_consultation_edit', {'id': consultation.id}) }}">edit</a>

    {{ include('consultation/_delete_form.html.twig') }}
   
    
{% endblock %}

templates/consultation/teleconsultation.html.twig
{% block title %}Teleconsultation{% endblock %}
{% block css %}

<link rel='stylesheet' type='text/css' media='screen' href="{{asset('styles/style.css')}}"> 

<link rel="preconnect" href="{{asset('https://fonts.gstatic.com')}}" crossorigin>
<link rel='stylesheet' href="{{asset('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300&family=Permanent+Marker&display=swap')}}">

{% endblock %}
{% block body %}

    <main>

     


        <!-- <div id="users-list"></div> -->

        <h1 id="site-title">Teleconsulltation</h1>
        <div id="join-wrapper">
            <input id="username" type="text" placeholder="Enter your name..." />
            <button id="join-btn">Join Stream</button>
        </div>
        <div id="user-streams" ></div>
        


        <!-- Wrapper for join button -->
        <div id="footer">
            <div class="icon-wrapper">
                <img class="control-icon" id="camera-btn" src="./assets/video.svg" />
                <p>Cam</p>
            </div>

            <div class="icon-wrapper">
                <img class="control-icon" id="mic-btn" src="./assets/microphone.svg" />
                <p>Mic</p>
            </div>

            <div class="icon-wrapper">
                <img class="control-icon" id="leave-btn" src="./assets/leave.svg" />
                <p>Leave</p>
            </div>
            
           
            
            
        </div>

    </main>
{% endblock %}
{% block js %}
<script src="https://download.agora.io/sdk/release/AgoraRTC_N.js"></script>
<script src='{{asset('js/script.js')}}'></script>
{% endblock %}